### ISSUE TITLE
Feature request: minimise-to-panel, alert sound, add one more human readable time

### ISSUE THREAD

**Issue by ghost** [parnoldx/timer#12]
Hi,
Excellent app, very handy!

I would like to make a few feature requests:

* Please add minimise to tray icon in panel. From there we can control it in the same manner we do when it is open in small window. Sometimes its makes window-switching (`Alt+Tab`) between all open window a bit tedious.
* Alert sound is not very noticeable. Double beep and little louder sound will be helpful.
* Please add `half hour` to acceptable human readable time format...

Thanks very much!

**Comment by worldofpeace** [comment]
Hi @pie-d 

> Please add `half hour` to acceptable human readable time format...

Do you mean when you input a time or time displayed when counting down?
> Alert sound is not very noticeable. Double beep and little louder sound will be helpful.

I agree the alert needs work.
> Please add minimise to tray icon in panel. From there we can control it in the same manner we do when it is open in small window. Sometimes its makes window-switching (Alt+Tab) between all open window a bit tedious.

I'm not sure what you mean by this.

**Comment by ghost** [comment]
1. I mean the time I input
2. Thanks
3. Have you ever used some electron based app? Slack, Discord? Or any app when you close the main window it minimises to panel. From there you can control and see the app status (as shown in screen shot below)  
It would be great if I can use this app from tray icon in panel, instead from small window (which is only current behaviour)  

![screenshot from 2018-02-20 23-10-31](https://user-images.githubusercontent.com/34853597/36439578-64bb01c8-1693-11e8-97b1-60a4aadc3c4e.png)

Also tray icon should give options to select time from recently used time values...  
Thanks

**Comment by parnoldx** [comment]
1. Mhh. Possible but probably not soon.
2. I will look at it.
3. Will not happen. On elementary, app indicators are unwanted. We could add actions to plank right click menu but not sure what should be there. I never missed something. So what actions you thinking about. 

In future please do one issue per request/bug.

**Comment by worldofpeace** [comment]
>Will not happen. On elementary, app indicators are unwanted. We could add actions to plank right click menu but not sure what should be there. I never missed something. So what actions you thinking about.

I thought app indicators could be used but they had to do more than just close and open the window.

**Comment by parnoldx** [comment]
> I thought app indicators could be used but they had to do more than just close and open the window.

Normal apps shouldn't need a indicator. Maybe stuff like system monitor but I don't see it is needed for the timer app.
Anyway just write down the actions that you would want there and I will think about a solution.

**Comment by parnoldx** [comment]
2 is fixed. Closing this issue.
