### ISSUE TITLE
A better sound when the timer completes?

### ISSUE THREAD

**Issue by ar0ra1** [parnoldx/timer#3]
Right now its a very short beep.
and possibly make th e window the gain focus and be on top when the timer is done ?

**Comment by parnoldx** [comment]
It already gains focus. Not sure what's a better sound is. If you provide some i will look at it. 3 beeps is imo not so short.

**Comment by ar0ra1** [comment]
https://www.youtube.com/watch?v=Xcx8PhORec0

something hard like the iphone alarm ^

**Comment by parnoldx** [comment]
I really don't like this sound :)
