### ISSUE TITLE
[help] build error : 'gstreamer-audio-1.0' not found

### ISSUE THREAD

**Issue by flameleo11** [parnoldx/timer#35]
$ meson build --prefix=/usr

The Meson build system
Version: 0.45.1
Source dir: /drive_d/work/tmp/timer-master
Build dir: /drive_d/work/tmp/timer-master/build
Build type: native build
Project name: com.github.parnold-x.timer
Native C compiler: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
Native Vala compiler: valac (valac 0.40.17)
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency glib-2.0 found: YES 2.56.4
Native dependency glib-2.0 found: YES 2.56.4
Native dependency gio-2.0 found: YES 2.56.4
Native dependency gio-unix-2.0 found: YES 2.56.4
Native dependency gobject-2.0 found: YES 2.56.4
Native dependency gtk+-3.0 found: YES 3.22.30

meson.build:20:0: ERROR: Native dependency 'gstreamer-audio-1.0' not found

A full log can be found at /drive_d/work/tmp/timer-master/build/meson-logs/meson-log.txt

i have tried :
install gstreamer in ubuntu 1804
https://gstreamer.freedesktop.org/documentation/installing/on-linux.html?gi-language=c

sudo apt-get install libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio

but still not working

please help

**Comment by ryonakano** [comment]
You need to run `sudo apt install -y libgstreamer-plugins-base1.0-dev`
